export const AGENCY_NAME = 'Trabelo'
export const AGENCY_DOMAIN = 'trabelo.com'
export const AGENCY_EMAIL = 'hello@trabelo.com'
export const AGENCY_CTA_NAV = 'Book a discovery call'
export const AGENCY_CTA_BODY = 'Book a discovery call'
export const AGENCY_CTA_SUBJECT = 'Website audit'
